services:
  # --- Backends ---
  lab_identity_service:
    build: ./lab_identity_service
    container_name: backend-uno
    ports:
      - "8080:8080"
    networks:
      - app-network

  lab_referral_service:
    build: ./lab_referral_service
    container_name: backend-dos
    ports:
      - "8081:8081"
    networks:
      - app-network

  lab_analysis_service:
    build: ./analysis_service
    container_name: backend-tres
    ports:
      - "8082:8082"
    networks:
      - app-network

  # --- Frontend ---
  lab_referral_system:
    build: ./lab_referral_system
    container_name: frontend-app
    ports:
      - "4200:80"
    depends_on:
      - lab_identity_service
      - lab_referral_service
      - lab_analysis_service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge